### ISSUE TITLE
Issue: Using var Instead of let in the Project

### ISSUE THREAD

**Issue by Srinath10X** [ashwanth10XS/wheather-report#1]
## Description

In our current project, the use of the var keyword for variable declarations is prevalent. However, var has several characteristics that can lead to bugs and maintenance challenges. It is recommended to transition to using let (or const where appropriate) for variable declarations to improve code quality and maintainability.

**Comment by ashwanth10XS** [comment]
gonna be fixed in next commit

**Comment by ashwanth10XS** [comment]
fixed
